[package]
name = "currency-exchange-client"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }

[[bin]]
name = "client"
path = "src/main.rs"